version: "3"
services:
  app:
    container_name: mydog-api-app
    build:
      context: .
      dockerfile: ./go/Dockerfile
    tty: true
    volumes:
      - ./backend:/go/src/mydog-api-app
    ports:
      - "9000:9000"
    environment:
      MONGO_DB_HOST: mongo-db
      MONGO_DB_PORT: 27017
    links:
      - "mongo-db:mongo-db"
  mongo-db:
    container_name: mydog-api-mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGODB_USER: root
      MONGODB_PASSWORD: root
  minio:
    container_name: mydog-api-minio
    image: minio/minio
    ports:
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: access_key
      MINIO_SECRET_KEY: secret_key
    command: server /export
  vue:
    container_name: mydog-api-front
    build:
      context: .
      dockerfile: ./vue/Dockerfile
    stdin_open: true
    tty: true
    command: /bin/sh
    volumes:
      - ./frontend:/src
    ports:
      - "8080:8080"