version: 2.1
jobs:
  checkout:
    docker:
      - image: circleci/golang:1.12 
    steps:
      - checkout:
            path: ~/mydog-rest-api
      - persist_to_workspace:
            root: ~/mydog-rest-api
            paths:
                - .

  build-test-backend:
    working_directory: ~/mydog-rest-api/backend
    docker:
      - image: circleci/golang:1.12 
    steps:
      - attach_workspace:
          at: ~/mydog-rest-api
      - run:
          name: create .env
          command: 'touch .env'
      - run:
          name: add variables .env
          command: |
            cat \<<EOF >> .env
            APP_ENV=prod
            DEFAULT_PORT=3000
            DB_HOST=mongo-db
            DB_PORT=27017
            DB_NAME=mydog-api
            EOF
      - run: go get github.com/lib/pq
      - run:
          name: go build test
          command: 'go build -o ./main'

  build-test-frontend:
    working_directory: ~/mydog-rest-api/frontend
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: .
      - run:
          name: vue build test
          command: 'npm run build'

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - checkout:
        filters:
          branches:
            only:
              - master
      - build-test-backend:
          filters:
            branches:
              only:
                - master
          requires:
            - checkout
      - build-test-frontend:
          filters:
            branches:
              only:
                - master
          requires:
            - build-test-backend
